### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ganyu69** [Sorrow446/MQ-DL#28]
Item 1 of 1:
リュックと添い寝ごはん - あたらしい朝
Track failed.
Traceback (most recent call last):
  File "mq-dl.py", line 382, in iter_track
  File "api\client.py", line 186, in get_tra_stream
  File "api\client.py", line 21, in make_call
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.napster.com/v2.2/streams?bitrate=96000&format=FLAC&track=tra.533232673

**Comment by Sorrow446** [comment]
Fixed. They changed something. Pushed to source.

**Comment by Ganyu69** [comment]
Thank you and can you fix Windows binaries?

**Comment by Sorrow446** [comment]
Yep. Will do today.

**Comment by Ganyu69** [comment]
Thank you 😃

**Comment by Sorrow446** [comment]
Up. Sorry for the wait.
