### ISSUE TITLE
Cannot use proxy

### ISSUE THREAD

**Issue by shinlw** [Sorrow446/MQ-DL#31]
Since the direct connection in my network can be very slow, I use proxy to speed up my downloading. It worked well without problems when using the first R2 release before, but not anymore in the latest release. Proxy tool: clash for windows 0.14.4
Thank you for providing us this tool!
```
PS E:\Program Files (x86)\MQ-DL> .\mq-dl_x86.exe -u https://content.mora-qualitas.com/artist/whiteeeen/album/aiuta-since-2007-

 _____ _____     ____  __
|     |     |___|    \|  |
| | | |  |  |___|  |  |  |__
|_|_|_|__  _|   |____/|_____|
         |__|

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 502, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 817, in __init__
  File "ssl.py", line 1077, in do_handshake
  File "ssl.py", line 689, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.napster.com', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:847)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mq-dl.py", line 506, in <module>
  File "mq-dl.py", line 28, in auth
  File "api\client.py", line 39, in auth
  File "api\client.py", line 20, in make_call
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.napster.com', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:847)'),))
[3264] Failed to execute script mq-dl
```

**Comment by Sorrow446** [comment]
You're welcome. Not sure what the problem could be as the latest version uses the same library (requests).

**Comment by hakumai7** [comment]
same bug

**Comment by PerkinsChao** [comment]
Same problem here... old version can download fast but latest version can't download with proxy
