### ISSUE TITLE
Forbidden for url Error

### ISSUE THREAD

**Issue by Leigo6677** [Sorrow446/MQ-DL#33]
Hello @Sorrow446 
Faced this error today

Item 1 of 1:
Item failed.
Traceback (most recent call last):
  File "mq-dl.py", line 515, in <module>
    main(media_type, _id)
  File "mq-dl.py", line 486, in main
    globals()[media_type](_id)
  File "mq-dl.py", line 420, in artist
    artist, art_ids = get_artist_meta(art_id)
  File "mq-dl.py", line 97, in get_artist_meta
    art_meta = client.get_art_meta(art_id)
  File "/content/drive/MyDrive/mq-dl/api/client.py", line 78, in get_art_meta
    'GET', "v2.2/artists/" + art_id, params=params, headers=headers)
  File "/content/drive/MyDrive/mq-dl/api/client.py", line 21, in make_call
    r.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.napster.com/v2.2/artists/Art.12701758?catalog=JP_MORAQUALITAS&lang=en-US&rights=2

Thanks for maintaning this Tool ❤

**Comment by Fukitsu** [comment]
I'm getting the same error, tried with album and artist URLs

**Comment by Sorrow446** [comment]
Another API change. Will fix later.

**Comment by Sorrow446** [comment]
Fixed. Pushed to source and Windows binary.

**Comment by Fukitsu** [comment]
Seems like it broke again. I'm getting 
Traceback (most recent call last):
  File "MQ-DL/mq-dl.py", line 380, in iter_track
    stream_url = client.get_tra_stream(specs['brate'], specs['fmt'],
  File "MQ-DL/api/client.py", line 186, in get_tra_stream
    j = self.make_call(
  File "MQ-DL/api/client.py", line 21, in make_call
    r.raise_for_status()
  File "/python/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.napster.com/v2.2/streams?bitrate=44100&format=FLAC&protocol=&track=tra.41391687
