### ISSUE TITLE
403 Client Error: Forbidden for url 

### ISSUE THREAD

**Issue by Fukitsu** [Sorrow446/MQ-DL#34]
Seems like it broke again. I'm getting:

Traceback (most recent call last):
File "MQ-DL/mq-dl.py", line 380, in iter_track
stream_url = client.get_tra_stream(specs['brate'], specs['fmt'],
File "MQ-DL/api/client.py", line 186, in get_tra_stream
j = self.make_call(
File "MQ-DL/api/client.py", line 21, in make_call
r.raise_for_status()
File "/python/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.napster.com/v2.2/streams?bitrate=44100&format=FLAC&protocol=&track=tra.41391687

**Comment by Leigo6677** [comment]
same here 😔

**Comment by Leigo6677** [comment]
same

**Comment by Sorrow446** [comment]
![B6t9EeA](https://user-images.githubusercontent.com/47045733/107620070-0ad55700-6c4c-11eb-86bc-5f5d2931a253.jpg)

**Comment by Sorrow446** [comment]
Fixed.
