### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by tientranthezomb** [Sorrow446/MQ-DL#35]
I updated to the new api and exe and this happened:
Traceback (most recent call last):
  File "mq-dl.py", line 381, in iter_track
    track['id'])
  File "api\client.py", line 189, in get_tra_stream
    return j['streams'][0]['url']
IndexError: list index out of range

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/MQ-DL/issues/32
