### ISSUE TITLE
 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by Fukitsu** [Sorrow446/MQ-DL#36]
It broke yet again, are they changing their API or something everyday or have they noticed the downloading? It seems to break after downloading a couple of albums.

Track failed.
Traceback (most recent call last):
  File "MQ-DL/mq-dl.py", line 380, in iter_track
    stream_url = client.get_tra_stream(specs['brate'], specs['fmt'],
  File "MQ-DL/api/client.py", line 187, in get_tra_stream
    j = self.make_call(
  File "MQ-DL/api/client.py", line 21, in make_call
    r.raise_for_status()
  File "python/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.napster.com/v2.2/streams?bitrate=48000&format=FLAC&protocol=&track=tra.432500816

**Comment by Leigo6677** [comment]
Downloads was fine with the new release, but after a few hours this happened again 😓

**Comment by Sorrow446** [comment]
Fixed.
