### ISSUE TITLE
Is not working.

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Sorrow446/MQ-DL#39]
python mq-dl.py -u https://content.mora-qualitas.com/?id=tra.411033134
                                                            _____ _____     ____  __
|     |     |___|    \|  |                                 | | | |  |  |___|  |  |  |__
|_|_|_|__  _|   |____/|_____|
         |__|
                                                           Signed in successfully.

Item 1 of 1:
Ed Sheeran - Shape of You
Track failed.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/MQ-DL/mq-dl.py", line 380, in iter_track
    stream_url = client.get_tra_stream(specs['brate'], specs['fmt'],
  File "/data/data/com.termux/files/home/MQ-DL/api/client.py", line 190, in get_tra_stream
    return j['streams'][0]['url']
IndexError: list index out of range
$

**Comment by Sorrow446** [comment]
Expired subscription.
