### ISSUE TITLE
A ferramenta parou de funcionar.

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Sorrow446/MQ-DL#44]
README.md     api          mq-dl.py
README_ja.md  config.json  requirements.txt
$ python mq-dl.py -u https://content.mora-qualitas.com/?id=tra.101921807

 _____ _____     ____  __
|     |     |___|    \|  |
| | | |  |  |___|  |  |  |__
|_|_|_|__  _|   |____/|_____|
         |__|

Signed in successfully.

Item 1 of 1:
Josh Groban - You Raise Me Up
Track failed.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/MQ-DL/mq-dl.py", line 380, in iter_track
    stream_url = client.get_tra_stream(specs['brate'], specs['fmt'],
  File "/data/data/com.termux/files/home/MQ-DL/api/client.py", line 188, in get_tra_stream
    j = self.make_call(
  File "/data/data/com.termux/files/home/MQ-DL/api/client.py", line 21, in make_call
    r.raise_for_status()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.napster.com/v2.2/streams?bitrate=44100&format=FLAC&protocol=&track=tra.101921807
$

**Comment by marcoreus111** [comment]
the same problem

**Comment by tientranthezomb** [comment]
also the same problem :(

**Comment by BTOWL** [comment]
also same problem

**Comment by Sorrow446** [comment]
Fixed privately. I'm not allowed to maintain it on GitHub because of legal issues. If you want it, get in touch.

**Comment by Misterio69** [comment]
> Fixed privately. I'm not allowed to maintain it on GitHub because of legal issues. If you want it, get in touch.

How can I get in touch with you brother? Thanks for the help.

**Comment by spitfire00** [comment]
> Fixed privately. I'm not allowed to maintain it on GitHub because of legal issues. If you want it, get in touch.

How can I get in touch with you brother? Thanks for the help.

**Comment by Sorrow446** [comment]
Sorrow#6826 or Reddit.

**Comment by seanluommd** [comment]
> 私下固定。由于法律问题，我不允许在GitHub上对其进行维护。如果需要，请保持联系。


Hello there! How can I contact you?

**Comment by windymryang** [comment]
> Sorrow#6826 or Reddit.

how can i contact you？

**Comment by seanluommd** [comment]
thank you! You have helped me~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sorrow446/MQ-DL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sorrow446/MQ-DL] A ferramenta parou de funcionar. (#44)





  
Sorrow#6826 or Reddit.
  
how can i contact you？

**Comment by johnrolan90** [comment]
> Fixed privately. I'm not allowed to maintain it on GitHub because of legal issues. If you want it, get in touch.

How can i contact you

**Comment by Kelseymaebunny** [comment]
I sent you a friend request on discord. can you help me?
