### ISSUE TITLE
Sry, whats wrong with it? I'm a noob for python, tried a whole night into it but it just not work.

### ISSUE THREAD

**Issue by Ragger97** [Sorrow446/MQ-DL#48]
Item 1 of 1:
Item failed.
Traceback (most recent call last):
  File "/home/ragger/Downloads/Programs/MQ-DL-master/mq-dl.py", line 515, in <module>
    main(media_type, _id)
  File "/home/ragger/Downloads/Programs/MQ-DL-master/mq-dl.py", line 486, in main
    globals()[media_type](_id)
  File "/home/ragger/Downloads/Programs/MQ-DL-master/mq-dl.py", line 445, in track
    tra_src_meta = client.get_tra_meta(tra_id)
  File "/home/ragger/Downloads/Programs/MQ-DL-master/api/client.py", line 127, in get_tra_meta
    j = self.make_call(
  File "/home/ragger/Downloads/Programs/MQ-DL-master/api/client.py", line 21, in make_call
    r.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.napster.com/v2.2/tracks/Tra.533232673?catalog=JP_MORAQUALITAS&lang=en-US&rights=2

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/MQ-DL/issues/44#issuecomment-826477770

**Comment by Ragger97** [comment]
> [#44 (comment)](https://github.com/Sorrow446/MQ-DL/issues/44#issuecomment-826477770)

I have sent a friend request, thanks for reply!
